export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const UPDATE_CONVERSION = "UPDATE_CONVERSION";
export const LOADING_CONVERSION = "LOADING_CONVERSION";
export const INVERT_CONVERSION = "INVERT_CONVERSION";
export const RESET_CONVERSION = "RESET_CONVERSION";
export const UPDATE_BASE_CURRENCY = "UPDATE_BASE_CURRENCY";
export const UPDATE_FOREIGN_CURRENCY = "UPDATE_FOREIGN_CURRENCY";
export const UPDATE_FORM_AMOUNT = "UPDATE_FORM_AMOUNT";
